# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Autonomous AI orchestrator for multi-repo development"
  homepage "https://github.com/Robin831/Forge"
  version "0.26.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Robin831/Forge/releases/download/v0.26.1/forge_0.26.1_darwin_amd64.tar.gz"
      sha256 "cb886705b9b78ea90e8e02b92a574b2b201c0f136678ee3d1083089fbd0fa226"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Robin831/Forge/releases/download/v0.26.1/forge_0.26.1_darwin_arm64.tar.gz"
      sha256 "27c53daa389149ed406e895f4bebc98edbd064f4b3c682c4486cc76fa816ce59"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Robin831/Forge/releases/download/v0.26.1/forge_0.26.1_linux_amd64.tar.gz"
      sha256 "f4e772befd8465d71114567d23dff6dd4a52109016854d3737b265dfccacdc55"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Robin831/Forge/releases/download/v0.26.1/forge_0.26.1_linux_arm64.tar.gz"
      sha256 "b5ebe7e465b89cd44c4b74318a099bf1ee3e72a03c63279ef2626d2c47188242"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge", "version"
  end
end
