# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Autonomous AI orchestrator for multi-repo development"
  homepage "https://github.com/Robin831/Forge"
  version "0.11.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Robin831/Forge/releases/download/v0.11.1/forge_0.11.1_darwin_amd64.tar.gz"
      sha256 "b828f087d99c3cda8a4b6ce0cb78e5a3d5193c5cf99091cf6767180676bfc847"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Robin831/Forge/releases/download/v0.11.1/forge_0.11.1_darwin_arm64.tar.gz"
      sha256 "f1076306f8e8542b2ad07a63b42a3e4d1009e66f5a5220d1172249e568887277"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Robin831/Forge/releases/download/v0.11.1/forge_0.11.1_linux_amd64.tar.gz"
      sha256 "e0bda6aa1a19cff31c7aefacd45aa56e1325caa2324982edc7772c200deb681a"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Robin831/Forge/releases/download/v0.11.1/forge_0.11.1_linux_arm64.tar.gz"
      sha256 "ae392e2a13704681d5cdc102db6cfed6099c204ff55804f7557b6fe790aac6c3"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge", "version"
  end
end
