# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Autonomous AI orchestrator for multi-repo development"
  homepage "https://github.com/Robin831/Forge"
  version "0.27.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Robin831/Forge/releases/download/v0.27.1/forge_0.27.1_darwin_amd64.tar.gz"
      sha256 "e3cca7c51461cd28c46a155ed4788ac05145b1d3cab0e80a65ee3b9f19fb099b"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Robin831/Forge/releases/download/v0.27.1/forge_0.27.1_darwin_arm64.tar.gz"
      sha256 "09d40773ecd859dcc5cdc0146550819d2139acb97a98ec4a8371cbbaedac260d"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Robin831/Forge/releases/download/v0.27.1/forge_0.27.1_linux_amd64.tar.gz"
      sha256 "9a7ef24d9977f0645c9323e3ee30049a6defd3ecfcfc811bf81a366f51c69150"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Robin831/Forge/releases/download/v0.27.1/forge_0.27.1_linux_arm64.tar.gz"
      sha256 "62cff77c24224dbe26e400c6eeea85027bf88b1a4640251facb8c1866fa979d3"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge", "version"
  end
end
